[package]
name = "cd-app"
version.workspace = true
edition.workspace = true

[dependencies]
cd-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }