[package]
name = "cd-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
rkyv = { version = "0.7.46", features = ["validation"], optional = true }

[features]
default = []
rkyv = ["dep:rkyv"]